### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Dnyaneshvn**

### CODE REVIEW

**Comment by CeoFred** [comment]
😂  what could be the issue champ?

**Comment by Dnyaneshvn** [comment]
just minor changes

**Comment by CeoFred** [comment]
create an issue for this, and i'll be happy to review.

**Comment by Dnyaneshvn** [comment]
will you merge this pr ?

**Comment by CeoFred** [comment]
nope, till you create an issue chief

**Comment by Dnyaneshvn** [comment]
issue created

**Pull request merged**
